name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Run `cargo clippy`
      run: cargo clippy --all-features
    - name: Check formatting
      run: cargo fmt -- --check
